harmon_ai:
  environment:
    repo_name: "AIRA"
    owner_name: "Sunwood-ai-labs"
    package_name: "AIRA"
    icon_url: "https://huggingface.co/datasets/MakiAi/IconAssets/resolve/main/AIRA.png"
    title: "AIRA"
    subtitle: "～AI-Integrated Repository for Accelerated Development～"
    website_url: "https://hamaruki.com/"
    github_url: "https://github.com/Sunwood-ai-labs"
    twitter_url: "https://x.com/hAru_mAki_ch"
    blog_url: "https://hamaruki.com/"

  product:
    important_message_file: "important_template.md"
    sections_content_file: "sections_template.md"
    output_file: "README_template.md"
    cicd_file_path: "publish-to-pypi.yml"
    cicd_main_path: "publish-to-pypi.yml"
    github_cicd_dir: ".github/workflows"
  
  development:
    output_dir: "C:/Prj/AIRA/.harmon_ai"

  main:
    main_dir: "C:/Prj/AIRA/"
    replace_readme: true

